### ISSUE TITLE
What is simplest Travis config for full Django matrix?

### ISSUE THREAD

**Issue by bittner** [tox-dev/tox-travis#77]
I'm maintaining a few Django packages, and running a matrix build against all supported Python/Django combinations is what we typically do.

Now I'm wondering, what the simplest Travis setup is for a full build matrix for Django (say, all Django versions >= 1.7 by their supported Python versions). I really want to avoid doing things twice, or things that overlap, in two different configuration files, `tox.ini` and `.travis.yml`.

Example `tox.ini` and `.travis.yml`
=============
Let's omit Python 3.2 for heaven's sake (all the packages seem to drop support anyway) and let's add `flake8`. Here's what I have come up with:

```ini
# -- FILE: tox.ini
[tox]
envlist =
    py{27,33,34}-django17
    py{27,33,34,35}-django18
    py{27,34,35}-django19
    py{27,34,35}-django110
    py{27,34,35,36}-django111
    flake8

[testenv]
commands =
    coverage run setup.py test
deps =
    coverage
    django17: Django>=1.7,<1.8
    django18: Django>=1.8,<1.9
    django19: Django>=1.9,<1.10
    django110: Django>=1.10,<1.11
    django111: Django>=1.11,<2.0

[testenv:flake8]
basepython = python2.7
deps = flake8
commands = flake8

[travis:env]
DJANGO =
    1.7: django17
    1.8: django18
    1.9: django19
    1.10: django110
    1.11: django111
```

This is already longer than I want, but probably as short as it gets. Now for the worse:

```yaml
# -- FILE: .travis.yml
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
matrix:
  exclude:
    - python: 3.5
      env: DJANGO=1.7
    - python: 3.6
      env: DJANGO=1.7
    - python: 3.6
      env: DJANGO=1.8
    - python: 3.3
      env: DJANGO=1.9
    - python: 3.6
      env: DJANGO=1.9
    - python: 3.3
      env: DJANGO=1.10
    - python: 3.6
      env: DJANGO=1.10
    - python: 3.3
      env: DJANGO=1.11
  include:
    - python: 2.7
      env: TOXENV=flake8

install:
  - pip install tox-travis
script:
  - tox
```

This is terribly long, and the `exclude:` section in the Travis configuration duplicates what is already specified in the Tox config, in a negative form, to make it all more complicated.  -- Is that really as simple as it gets, for a full build matrix?

The result we get looks somewhat like [Travis build #288326510](https://travis-ci.org/jcassee/django-analytical/builds/288326510), which is fine.

Can We Derive Environments Automatically?
==========================
I prefer to specify my "build matrix" in Tox, because that ensures that I can run the same set of checks and tests locally _and_ on a CI infrastructure. I only need to change a single file, that's how I want it.

Can I configure a much simpler `.travis.yml` that lets me avoid doing the same work twice?  Maybe have both the `env:` section and the `matrix: exclude: ` section be built automagically? With the same result as above, each combination listed as a separate job in the Travis build.

```yaml
# -- FILE: .travis.yml
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8

install:
  - pip install tox-travis
script:
  - tox
```
(That file doesn't do it, which is part of the question.)

Is something like that feasible at all? Is that already possible? If yes, what is missing for a concise solution?

What I Have Stopped Doing
===================
Let me mention what I have stopped doing, mainly due to the [limitations the Travis build images have](https://github.com/travis-ci/travis-ci/issues/4990) for Python since well over a year.

```yaml
#-- FILE: .travis.yml
language: python
python: "3.5"
install:
  - pip install tox
script:
  - tox
env:
  # NOTE: To generate (update) the env list run
  # $ tox -l | sort | xargs -I ITEM echo "  - TOXENV="ITEM
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py34-django111
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
  - TOXENV=py35-django111
  - TOXENV=py36-django111
```

This is less stable than builds with dedicated Python versions and requires some manual maintenance (demonstrated by the NOTE comment in the code). It is technically though the result we need:

- The `env:` section lists the jobs we would want to otherwise generate with a `tox-travis` solution,
- or by simply a  `matrix: include: ` section with a full list of Python/Django combinations (which would be double the lines of code of the `env:` section, though).

Please let me know your thoughts!
